# ================== DATASET PATH ==================
path: /home/soni/Desktop/Octane/RekTNet/yolo_pose_dataset
train: train/images
val: val/images

# ================== CLASSES ==================
nc: 1
names: ['cone']

# ================== POSE SETTINGS ==================
task: pose
kpt_shape: [8, 3]

# awk '{print NF}' yolo_pose_dataset/train/labels/*.txt | sort | uniq OUTPUT should be --> 29